### ISSUE TITLE
hds + playlist: play button stays put after switching to a different item

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flash#103]
Demo: http://fdc.2tvod.com/cs16.html

**Comment by danrossi** [comment]
They are trying to use bwcheck plugin without any detection url or dynamic config, which they require the dev plugins anyway. Not setup correctly and causing an error. Perhaps all they need is to configure the bitrateselect plugin instead. It's an MBR feed and causing an error internally trying to switch to a quality.

**Comment by danrossi** [comment]
Its a multi level file which should be detecting and parsing. Have not used these before, they should be packaged into the one file.

**Comment by danrossi** [comment]
That is correct the multilevel parser of f4m v2 needs to be plugged in and should be trivial to do no worries.

**Comment by danrossi** [comment]
No just an update, I did implement it but needs to be configured if using multi level feeds see

f4m: {
  version: 2
}

**Comment by danrossi** [comment]
There is still some other issues however, all the parsed feeds have null bitrates so there is something up with their feed still.

**Comment by danrossi** [comment]
If they configure the version to 2, they need to fix their feed up still see

```
<media href="http://smc.2tvod.com/11/1PJaSZgTmh/abr/abr_1PJaSZgTmh_350k.mp4.f4m" bitrate="350k"/>
```

needs to be a number only

```
<media href="http://smc.2tvod.com/11/1PJaSZgTmh/abr/abr_1PJaSZgTmh_350k.mp4.f4m" bitrate="350"/>
```

It plays but no bitrate selection etc will work.

**Comment by prasaar** [comment]
Hi Dan, I have fixed the issue with bitrate in the manifest file. However the I still see the Buffering and Play Button Overlays stay put after switching to the next clip. I have tested the same settting with http(default progressive download)  and rtmp plugins and they work fine. Issue is only with httpstreaming.

**Comment by danrossi** [comment]
you are using mbr feeds, and the bwcheck config is doing nothing and incorrectly configured. So perhaps setup the bitrateselect one instead so it can configure the playback correctly with a default rate. ie urlResolvers: [ "f4m", "bitrareselect" ]

**Comment by prasaar** [comment]
http://2tvod-fd.s3.amazonaws.com/cs17.html
This is a new page using bitrateselect. I have not setup the css+div for the bitrate selections. The plugin uses the default bitrate for each clip. 
Problem still persists when switching from one clip to another. 
One thing I noticed is that in case HDS  we get 2 Netstream notify messages (a) Pause ( NetStream.Pause.Notify )  (b) Stop( NetStream.Play.Stop)  after  hitting the Next clip button. Just a hunch not sure.

**Comment by prasaar** [comment]
Compared the event flow and logs for   http(progressive download) , RTMP and HDS.  
Only in HDS do we get an event related to the old clip after opening a connection for the new clip. 
This is because the underlying layer from OSMF is closing the stream for the previous clips fragments after it receives a connection request for the new clips stream.
This raises a NetStream.Play.Stop event. The event framework has market the new clip as current. It now  applies the stop event to the new clip.  This causes the Play button to appear once again. I have turned on extensive logging on the cs16.html  and cs17.html page which shows up on the browser console. The logs generated after clicking the Next Clip button show the above event flow.

**Comment by prasaar** [comment]
HI Dan,

I added the following code in NetStreamControllingStreamProvider.as

# Function : doStop

```
            /* Section Added by Arun Prasad for testing.*/
            /* if the provider is httpstreaming then close the stream and make it null */
            if (clip.provider == "httpstreaming")
            {
              log.debug("NetStreamControllingStreamProvider Arun Prasad added code to close netstream");
              netStream.close();
              _netStream = null;
            }
            else
            {
            /* End of Section added by Arun Prasad */

            //#9 when replaying from stopping, connection does not receive callbacks anymore.
            //netStream.client = new NullNetStreamClient();
            netStream.pause();
            netStream.seek(0);
```

# 

It works because similar  to http and  rtmp only one  stop event is raised.
The long term fix should be to refactor the httpstreaming  Provider.

Question : How do I get this fix in our licensed version flowplayer.swf?

**Comment by danrossi** [comment]
https://dl.dropboxusercontent.com/u/3394987/flowplayer.bwcheck-httpstreaming-3.2.13-dev.zip
https://dl.dropboxusercontent.com/u/3394987/flowplayer.f4m-3.2.10-dev.zip
https://dl.dropboxusercontent.com/u/3394987/flowplayer.httpstreaming-3.2.11-dev.zip

The playlist issue was fixed in the dev sources but not released as yet. You can try these versions I just made for you if possible. You are right there is a bit of code to trigger the player stop on a stop event but that was supposed to be for live streams only and when there is no more playlist items so has been fixed. 

That bwcheck version will enable you to choose the dynamic config and do dynamic switching correctly.

**Comment by prasaar** [comment]
Hi Dan, The fix for the playlist works real smooth. 
( http://2tvod-fd.s3.amazonaws.com/cs16fix.html )
However the bwcheck dynamic config does not seem to work for httpstreaming.  
It always picks up the lowest bitrate and plays only that. My download speed in HK is 40 Mbps.
I think the metrics measurement  are not kicking in to trigger the dynamic switching for httpstreaming.

**Comment by prasaar** [comment]
did some testing of configs under 
 http://2tvod-fd.s3.amazonaws.com/cs16fix2.html 
 http://2tvod-fd.s3.amazonaws.com/cs16fix3.html 
and same problem the QoS and NetMetrics for http streaming are not triggering.

I had fixed this issue in my lcoal codebase of an old version of flowplayer plugins  

# File :  BwCheckProvider.as

(a)  Turning on  DownLoadRatioRule with true  to apply it  i.e.  addRule("ratio", rules, new DownloadRatioRule(metrics,true));
(b) onStart would enable dynamic
(c) will not check on BwStreamSelectionManager (since its not being used for httpstreaming dynamic )
       Replace 
               if (_config.dynamic && _streamSelectionManager is BWStreamSelectionManager) 
       With
                if (_config.dynamic && _provider.type=="httpstreaming") 

# 

This uses the default DownloadRatioRule in OSMF. Not perfect but  at least triggers it. A mechanism to appliy the ratio config in this rule would be great.

**Comment by danrossi** [comment]
Turn the screen size rule off

qos:{"frames":false,"screen":false}

**Comment by prasaar** [comment]
Done. Same behaviour. It plays only the lowermost bitrate.
I dont see any HttpMetrics related messages in the logs.
Url:   http://2tvod-fd.s3.amazonaws.com/cs16fix4.html

# 

 bwcheck:{
             url:"flowplayer.bwcheck-httpstreaming-3.2.13-dev.swf",
             provider:"httpstreaming",
             dynamic:true,
             checkOnStart:true,
             dynamicBuffer:true,
             qos:{"frames":false,"screen":false}
   },

 clip:{autoPlay:true,autoBuffering:true,mute:false,provider:"httpstreaming",urlResolver:   ["f4m","bwcheck"],bwcheck:true, subTitle:"Vimantra"
 },

#

**Comment by danrossi** [comment]
disable checkOnStart: true as you don't have a url configured for that. It should begin switching.

**Comment by danrossi** [comment]
this is also not required bwcheck:true

**Comment by prasaar** [comment]
Tried this under url: http://2tvod-fd.s3.amazonaws.com/cs16fix5.html
Same result. It does not trigger any dynamic switching and continues playing the lowest bitrate.

# 

bwcheck:{
                                                        url:"flowplayer.bwcheck-httpstreaming-3.2.13-dev.swf",
                                                        provider:"httpstreaming",
                                                        dynamic:true,
                                                        dynamicBuffer:true
                                                        }
                                                 },
                                clip:{autoPlay:true,autoBuffering:true,mute:false,provider:"httpstreaming",urlResolver:["f4m","bwcheck"],subTitle:"Vimantra"
                                      },

# 

Logs  for bwcheck from javascript console:

# 

[LOG] time 18:57:57.902 :: org.flowplayer.bwcheck::BwCheckProvider : onConfig(_)
[LOG] time 18:57:57.918 :: org.flowplayer.bwcheck::BwCheckProvider : onConfig(), dynamic true
[LOG] time 18:57:57.985 :: org.flowplayer.bwcheck::BwCheckProvider : onLoad()
[LOG] time 18:57:59.894 :: org.flowplayer.bwcheck::BwCheckProvider : applyForClip() ? null
[LOG] time 18:57:59.896 :: org.flowplayer.bwcheck::BwCheckProvider : applyForClip() ? null
[LOG] time 18:57:59.903 :: org.flowplayer.bwcheck::BwCheckProvider : onStart() clip == null
[LOG] time 18:57:59.905 :: org.flowplayer.bwcheck::BwCheckProvider : applyForClip() ? null
[LOG] time 18:57:59.908 :: org.flowplayer.bwcheck::BwCheckProvider : applyForClip() ? null

#

**Comment by danrossi** [comment]
flowplayer("player", "http://2tvod-fd.s3.amazonaws.com/players/flowplayer/content/swf/flowplayer.swf",
    {
        log: { level: 'debug', filter: 'org.osmf._, org.flowplayer.f4m._, org.flowplayer.httpstreaming._, org.flowplayer.bwcheck._' },

```
    playlist:[
                    {   url:"abr_1PJaSZgTmh.f4m",
                        title:"Video 1"
                    },
                    { url:"abr_6zilG1TCyT.f4m",
                      title:"Video 2"
                    },
                    {
                      url:"abr_1BSkb5Tm4j.f4m",
                     title:"Video 3"
                    }
            ],
    clip: {
        baseUrl:"http://smc.2tvod.com/11/1PJaSZgTmh/abr/",
                   urlResolvers: ['f4m','bwcheck'],
                   provider: 'httpstreaming',
        autoPlay: true,

        bitrates: [
            { bitrate: 150},
            { bitrate: 350, isDefault: true},
            { bitrate: 700}
        ]



    },
    plugins:  {
        f4m: {
            url: 'flowplayer.f4m-3.2.10-dev.swf',
    version: 2,

        },
        httpstreaming: {
            url: 'flowplayer.httpstreaming-3.2.11-dev.swf'
        },
        bwcheck: {
            url: 'flowplayer.bwcheck-httpstreaming-3.2.13-dev.swf',
            dynamic: true,
    qos: {screen: false},

            // show the selected file in the content box. This is not used in real installations.
            onStreamSwitchBegin: function (newItem, currentItem) {
                console.log("Will switch to: " + newItem.streamName +
                 " from " + currentItem.streamName);

            },
            onStreamSwitch: function (newItem) {
               console.log('content').setHtml("Switched to: " + newItem.streamName);

            }
        }

    }
});
```

this config switches and stays at 700 and doesn't switch down. There is alot of junk in the configs so I cannot be sure where it is but perhaps first try and take out the analytics plugin whatever it is. I'll supply a version of the plugin(s) with debug logging.

**Comment by danrossi** [comment]
https://dl.dropboxusercontent.com/u/3394987/flowplayer.httpstreaming-3.2.11-dev.zip
https://dl.dropboxusercontent.com/u/3394987/flowplayer.bwcheck-httpstreaming-3.2.13-dev.zip
https://dl.dropboxusercontent.com/u/3394987/flowplayer.f4m-3.2.10-dev.zip

backup the old ones and add the debug versions. I removed some logging in the f4m. It is changing for me fine. Perhaps it is this qos: {screen: false}, all along and I reckon should be disabled by default as it stitches alot of people up. That says if the width is less than the screen or less than maxWidth dont let it switch. Perhaps try playing around with disabling that or setting maxWidth to the maximum dimensions of the 700k.

**Comment by prasaar** [comment]
Hi Dan,  My mistake ... 
My config had  urlResolver["f4m","bwcheck"]  instead of  urlResolvers["f4m", "bwcheck"]   ..(plural with the extra s)
As a result it was applying only the first f4m   url resolver and playing the default first bit rate.

**Comment by danrossi** [comment]
Yes try to use the common clip object for common options that does not need to go into the playlist config. Let me know how the switching goes for you as it was newly refactored a few months ago and yet to be released still ;)  The older version depended on OSMF 1 and that single rule you mentioned had obvious problems they completely redid the metrics specially for segment streaming so the plugins had to be changed to suit

**Comment by danrossi** [comment]
closing this for now thanks
