### ISSUE TITLE
enhance ipad plugin to fall back to html5 on Android

### ISSUE THREAD

**Issue by bbbo** [flowplayer/flash#112]
is this possible? right now on many devices Flopwlayer just says "install Flash!"

**Comment by danrossi** [comment]
Probably a good idea seeing that they've purposely blocked flash since 4.2 even with it installed and samsung is still advertising it available on their tablets :o Basically video on android is a mess right now because they try to fix something that wasn't broken. My phone has a quad core cpu ffs lol.

**Comment by bbbo** [comment]
it would be cool to have an addtional androidUrl property whihca can link to rstp streams too.

**Comment by phloxic** [comment]
Implementing an additional url is not a problem. But what about the API or playlists? I don't think this will report events to the html5 video js api? Any ideas? Would this just be a dumb url for single clips?

**Comment by danrossi** [comment]
Good call I believe that is what people are saying to do for live streams, it's a mess isn't it. rtsp streams just for android so much for single formats that everyone wants :O Back to trying to fix what is not broken ;) 

I haven't completed it yet but I've started handing this out to people who are using my fp3 plugins

http://flowplayer.electroteque.org/flashfp3/fp5

**Comment by anssip** [comment]
Nope. Just send the peeps to Flowplayer HTML5.
