### ISSUE TITLE
allow bufferLength: 0

### ISSUE THREAD

**Issue by bbbo** [flowplayer/flash#114]
to avoid gap in live streams. see http://flowplayer.org/forum/#!/moot/12404

**Comment by danrossi** [comment]
Probably not a good idea it would trigger rebuffers. 2 seconds is a standard buffer length.

**Comment by bbbo** [comment]
but it's the only way (or buffer length 0.1 etc) to avoid the gap mentioned in http://flowplayer.org/forum/#!/setup_configuration#12404_how_to_avoid_ (correct link to the fourm entry mentioned above). unless you know a better way?

**Comment by bbbo** [comment]
@anssip I think you verified the need when we checked the forum entry?

**Comment by danrossi** [comment]
What is wrong setting 0.1 that won't be treated as an empty config. Did you try it ?  0.1 is pretty insane also especially for live stream over latency. I don't understand anything that is in that message. I'd set it to 2 seconds at least.

**Comment by bbbo** [comment]
as @anssip  said: with the standaed bufferLength, Flowplayer after some run time is up to a minute or more behind strobe playing the same stream. the user proved that by livestreaming images from a clock, oover time the gap between both showing different times widened. This did not happen for Anssi with bufferLength: 0.

**Comment by danrossi** [comment]
I still don't understand what is going on sorry i can't see anything is there a video ? what do you mean behind strobe ?

**Comment by bbbo** [comment]
the user deleted the video in the meantime.

situation: one rtmp stream showing a clock.
open stream in strobe player and Flowplayer simulatenously; both show for example: 12:00h Let them continue to run. Aftee 3 hours, strobe will show the clock at 15:00h and Flowplayer will show the clock at 14:58. Set buffer lenght to 0 in a tets build and both will show the same time. Ask Anssi, he did some experiments here.

We got similar reports before about a lag.

**Comment by danrossi** [comment]
To me that's a bad example as it's increasing latency trying to stream two streams at once. The issue is latency here. I thought you meant a lag between what is being streamed and what is being subscribed. If that is the case too many factors there like distance between the encoder and server and then server to client. Strobe media is doing a buffer optimisation which I added something into the rtmp plugin just recently to help with buffers on a buffer empty which I had added into HDS also, perhaps that is causing some problem ? Please confirm. 

I just grepped the player code, they do not do buffer enhancements for live streams, only for dynamic switching, the default live buffer within the OSMF code is 0.1 for live streams, and then it changes it to 2 on playback.

**Comment by danrossi** [comment]
might be an idea to implement that into the rtmp plugin perhaps.

**Comment by danrossi** [comment]
im taking the buffer bit out of rtmp for now that was only for HDS it seems.

**Comment by anssip** [comment]
The current dev version accepts clip.bufferLength: 0
