### ISSUE TITLE
Captions Plugin: Emtpy srt causes autoPlay not to work

### ISSUE THREAD

**Issue by ohanyan** [flowplayer/flash#65]
If there's an error with the srt file, the captions plugin throws an error.  This results in the video not starting.  It would be useful to dispatch an error that can be caught and handled.

Otherwise, one must first get the srt resource, check if empty (or any other error), before supplying to the captions plugin.

**Comment by danrossi** [comment]
Do you have a demo page for this ? I'm sure its easy to fix.

**Comment by ohanyan** [comment]
Url with working SRT http://s3.amazonaws.com/vikitemp/working.html
Url with empty SRT http://s3.amazonaws.com/vikitemp/empty.html
Url with nonexistent SRT  http://s3.amazonaws.com/vikitemp/wrong.html

On chrome it shows 300: Player initialization failed: Error: Unrecognized captions file extension
On firefox (i have flash debugger), it throws a parsing error

For the case where the SRT url is wrong, it actually works.  Should probably behave the same way with invalid SRT.

Thanks!

**Comment by danrossi** [comment]
Ok it is throwing an error when it probably should just not generate captions for that playlist item. Its not recognising a valid captions file and throwing an error.

**Comment by danrossi** [comment]
Hi there, I just had a look, I don't think if you were to configure subtitles it would be empty, it's either configured on the clip or not. And it seems to handle missing files ok. An empty configured subtitles file seems like a localised issue to me. Can you give me an idea why it would be empty ?

**Comment by netcaptioning** [comment]
I had a similar issue.  I was getting the same error (300: player initilization failed: Error: unrecognized captions file extension) and I couldn't figure out why.
It turned out it was the formatting of the SRT file.  Make sure your file follows this exact formatting:

1
00:00:03,500 --> 00:00:06,500
What do you look for in
a recording studio? 

2
00:00:06,500 --> 00:00:08,433
Great drum tones?

3
00:00:08,433 --> 00:00:10,767
Clean vocal takes?

After I fixed my SRT file, the captions work perfectly.

**Comment by danrossi** [comment]
Hi there I think the issue with this one is that the configured caption feed is empty therefore its failing to parse. I might then put something in place to ignore parser failures.

**Comment by danrossi** [comment]
not sure if there is anything to fix here closing for now if possible.
