### ISSUE TITLE
content plugin: cursor behaves differently over text in normal and fullscreen mode

### ISSUE THREAD

**Issue by phloxic** [flowplayer/flash#68]
Reproducible with our own standalone sample:
http://flash.flowplayer.org/demos/standalone/plugins/flash/index.html
Hover over text area in normal mode: cursor crosshair
Hover over text area in fullscreen mode: cursor default
See: http://flash.flowplayer.org/forum/5/104565
I agree with user that cursor should always be default - there's no way of styling the cursor directly (pointer for anchor tags works).

**Comment by danrossi** [comment]
What OS ? Its not selectable text therefore no cursor I think.

**Comment by phloxic** [comment]
1) It _is_ selectable text. Did you try? - but good point.
2) different cursor in fullscreen mode.
As indeed the cursor for selectable text is crosshair, I retract my vote, and say that it should be crosshair in fullscreen too.

**Comment by danrossi** [comment]
I dont see the cursor change for me, as you would with the button mode hand cursor. What OS ?

**Comment by phloxic** [comment]
MacOS - not _hand_ cursor (pointer), but crosshair (selectable text) in normal mode, and default (arrow) in fullscreen.
crosshair makes sense because I can select (and copy) the text.

**Comment by anssip** [comment]
This happens because flash has until recently disabled interactivity (text input) in fullscreen mode. It's possible to enable interactivity with Flash 11.3 and later, see here: http://help.adobe.com/en_US/as3/dev/WS58a13becbbb904c7-28cf6d32136e60de784-8000.html

We could perhaps add fullscreen interactive mode to the player. Something to test at least, there will be a different kind of notification when entering interactive full screen, and the user has to press a button to acknowledge it: "An overlay message appears when the content enters full-screen interactive mode. The message displays the domain of the full-screen page, instructions on how to exit full-screen mode, and an Allow button. The overlay persists until the user clicks Allow, acknowledging they are in full-screen interactive mode."

This would be a useful feature for the content and viral videos plugins! We need an additional option to enable this, because there is this additional click that is required from the user. Should be an option in the player level.

The viral videos plugin needs to be changed to work properly in interactive fullscreen. Currently i think there are some tweaks to not display for example the email tab on fullscreen.

**Comment by danrossi** [comment]
I still don't get what you are on about because I just see an arrow pointer when not in fullscreen however I have discovered something which you may be on about. The hand cursor for all "button mode" sprites is missing in normal mode for some reason, and then I get the hand cursor in fullscreen for all "button mode" sprites. It's been bugging me and i'll look into that first.

**Comment by danrossi** [comment]
the issue I  discovered is a chrome related bug. Testing against other browsers now

**Comment by danrossi** [comment]
i now see the pointers change in firefox not chrome though.

**Comment by danrossi** [comment]
ok so the text is selectable by default if this is disabled the pointer changes to an arrow. in fullscreen its likely not selectable because of the issue above. should we change them to be not selectable ?

**Comment by danrossi** [comment]
did you want to add this in ? The issue being is it might need to be a config option on the player as it would have to be on the fullscreen manager directly. Then on top of this it would have to use strings for compilation instead of the display state contants or else we've broken 10.0 compatibility. There is so many good api functions like native json parsing 11.3 would be good to support :) So within the config option it would need to check the player version for 11.3 or above.

**Comment by danrossi** [comment]
correction, just saw this now a common clip config might be sufficent and easy to implement, interactiveFullscreen or fullscreenInteractive or something like that.

**Comment by danrossi** [comment]
and a change on the javascript api for the embedding.

**Comment by danrossi** [comment]
if the text is not made selectable then the cursor will stay an arrow for now, or implement this other feature.

**Comment by danrossi** [comment]
the chrome bug I discovered is also happening on youtube. possibly not fixable.

**Comment by danrossi** [comment]
the bug is related to this which means the text is unselectable in chrome

https://code.google.com/p/chromium/issues/detail?id=136054

**Comment by danrossi** [comment]
what is the resolution for this can it be closed ?
