### ISSUE TITLE
Custom Plugin: Compile errors when custom class implements Plugin (v3.2.16, v3.2.15)

### ISSUE THREAD

**Issue by estornes** [flowplayer/flash#80]
Hello I'm new here,

I'm developing a custom plugin. I need to interact with flowplayer's event, for that I need to implement org.flowplayer.model.Plugin interface. I do it, but when I compile multiple errors occur. For example:

NetStreamControllingStreamProvider.as, Line 46-> 1120: Access of undefined property FLASH_10_1.

PlayListController.as, Line 332-> Warning: 1060: Migration issue: The method stop is no longer supported.  For more information, see MovieClip.stop()..

Has anybody faced the same issue?

Thank you

**Comment by estornes** [comment]
I forgot to mention I'm using Flash CS4.

**Comment by danrossi** [comment]
Hi please follow the docs, this question is best sent to the forums if possible

http://flash.flowplayer.org/documentation/developer/development-environment.html
http://flash.flowplayer.org/documentation/developer/writing-flash-plugins.html

You need to compile via ant rather than use the flash ide. The ant task includes all the required compiler constants.

**Comment by estornes** [comment]
I'll use ant. Thank you.
